/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type esMessage from '../locales/es/messages.json';
import type hiMessage from '../locales/hi/messages.json';
import type roMessage from '../locales/ro/messages.json';
import type ruMessage from '../locales/ru/messages.json';
import type ukMessage from '../locales/uk/messages.json';

export type MessageKey = keyof typeof enMessage &
  keyof typeof esMessage &
  keyof typeof hiMessage &
  keyof typeof roMessage &
  keyof typeof ruMessage &
  keyof typeof ukMessage;

export type DevLocale = 'en' | 'es' | 'hi' | 'ro' | 'ru' | 'uk';
