/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type roMessage from '../locales/ro/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof roMessage;

export type DevLocale = 'en' | 'ro';
