const sensitiveKeywords = [
  'okta',
  'authorization',
  'oai-sc',
  'access_token',
  'refresh_token',
  'secret',
  'password',
  'api_key',
  'token',
  'auth_token',
  'id_token',
  'oauth_token',
  'jwt',
  'key',
  'private_key',
  'public_key',
  'session_token',
  'csrf_token',
  'sso_token',
  'encryption_key',
  'decryption_key',
  'username',
  'email',
  'user_id',
  'social_security_number',
  'ssn',
  'card_number',
  'cc_number',
  'credit_card',
  'cvv',
  'expiration_date',
  'bank_account',
  'routing_number',
  'iban',
  'bic',
  'pin',
  'api_secret',
  'auth_secret',
  'client_id',
  'client_secret',
  'aws_access_key',
  'aws_secret_key',
  'azure_key',
  'gcp_key',
  'stripe_key',
  'webhook_secret',
  'master_key',
  'vault_key',
  'sid',
  'sidcc',
  'gmail_at',
];

// Compile regex patterns for case-insensitive matching of sensitive keywords
export const sensitiveKeywordsPatterns = sensitiveKeywords.map(keyword => {
  const pattern = new RegExp(`\\b${keyword.replace(/_/g, '[_-]?')}\\b`, 'i');
  return { pattern };
});
