export enum Plan {
  FREE = 'FREE',
  STARTER = 'STARTER',
  BASIC = 'BASIC',
  PLUS = 'PLUS',
  INDIVIDUAL = 'INDIVIDUAL',
  INSPECTOR = 'INSPECTOR',
  PROFESSIONAL = 'PROFESSIONAL',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}
